# -*- coding: utf-8 -*-
"""
/***************************************************************************
 sediGoPro
                                 A QGIS plugin
 Manage image remotly capture with a GoPro camera
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2019-04-06
        copyright            : (C) 2019 by E. Poizot / Cnam-Intechmer (France)
        email                : emmanuel.poizot@lecnam.net
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load sediGoPro class from file sediGoPro.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .sedigopro import sediGoPro
    return sediGoPro(iface)
