# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sedigopro_dialog_base.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_sediGoProDialogBase(object):
    def setupUi(self, sediGoProDialogBase):
        sediGoProDialogBase.setObjectName("sediGoProDialogBase")
        sediGoProDialogBase.resize(603, 500)
        self.button_box = QtWidgets.QDialogButtonBox(sediGoProDialogBase)
        self.button_box.setGeometry(QtCore.QRect(510, 460, 81, 32))
        self.button_box.setOrientation(QtCore.Qt.Horizontal)
        self.button_box.setStandardButtons(QtWidgets.QDialogButtonBox.Ok)
        self.button_box.setObjectName("button_box")
        self.imageGoProViewer = QtWidgets.QGraphicsView(sediGoProDialogBase)
        self.imageGoProViewer.setGeometry(QtCore.QRect(10, 10, 411, 311))
        self.imageGoProViewer.setObjectName("imageGoProViewer")
        self.connectionStatusLabel = QtWidgets.QLabel(sediGoProDialogBase)
        self.connectionStatusLabel.setGeometry(QtCore.QRect(450, 20, 108, 19))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(204, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(204, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(190, 190, 190))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.connectionStatusLabel.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.connectionStatusLabel.setFont(font)
        self.connectionStatusLabel.setObjectName("connectionStatusLabel")
        self.connectGoProCameraButton = QtWidgets.QPushButton(sediGoProDialogBase)
        self.connectGoProCameraButton.setGeometry(QtCore.QRect(450, 50, 111, 24))
        self.connectGoProCameraButton.setObjectName("connectGoProCameraButton")
        self.setWorkingDirectoryButton = QtWidgets.QPushButton(sediGoProDialogBase)
        self.setWorkingDirectoryButton.setGeometry(QtCore.QRect(450, 120, 145, 24))
        self.setWorkingDirectoryButton.setObjectName("setWorkingDirectoryButton")
        self.label = QtWidgets.QLabel(sediGoProDialogBase)
        self.label.setGeometry(QtCore.QRect(450, 200, 76, 16))
        self.label.setObjectName("label")
        self.groupBox = QtWidgets.QGroupBox(sediGoProDialogBase)
        self.groupBox.setGeometry(QtCore.QRect(10, 330, 301, 141))
        self.groupBox.setObjectName("groupBox")
        self.prefixTextTagLineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.prefixTextTagLineEdit.setGeometry(QtCore.QRect(10, 100, 201, 24))
        self.prefixTextTagLineEdit.setMaxLength(30)
        self.prefixTextTagLineEdit.setObjectName("prefixTextTagLineEdit")
        self.tagImageButton = QtWidgets.QPushButton(self.groupBox)
        self.tagImageButton.setGeometry(QtCore.QRect(10, 30, 81, 24))
        self.tagImageButton.setObjectName("tagImageButton")
        self.llRadioButton = QtWidgets.QRadioButton(self.groupBox)
        self.llRadioButton.setGeometry(QtCore.QRect(110, 30, 39, 22))
        self.llRadioButton.setChecked(True)
        self.llRadioButton.setObjectName("llRadioButton")
        self.lrRadioButton = QtWidgets.QRadioButton(self.groupBox)
        self.lrRadioButton.setGeometry(QtCore.QRect(150, 30, 40, 22))
        self.lrRadioButton.setObjectName("lrRadioButton")
        self.ulRadioButton = QtWidgets.QRadioButton(self.groupBox)
        self.ulRadioButton.setGeometry(QtCore.QRect(200, 30, 41, 22))
        self.ulRadioButton.setObjectName("ulRadioButton")
        self.urRadioButton = QtWidgets.QRadioButton(self.groupBox)
        self.urRadioButton.setGeometry(QtCore.QRect(250, 30, 43, 22))
        self.urRadioButton.setObjectName("urRadioButton")
        self.numImageSPinBox = QtWidgets.QSpinBox(self.groupBox)
        self.numImageSPinBox.setGeometry(QtCore.QRect(230, 100, 61, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.numImageSPinBox.setFont(font)
        self.numImageSPinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.numImageSPinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.PlusMinus)
        self.numImageSPinBox.setObjectName("numImageSPinBox")
        self.whiteTagTextButton = QtWidgets.QPushButton(self.groupBox)
        self.whiteTagTextButton.setGeometry(QtCore.QRect(180, 60, 50, 24))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.whiteTagTextButton.setPalette(palette)
        self.whiteTagTextButton.setAutoFillBackground(False)
        self.whiteTagTextButton.setText("")
        self.whiteTagTextButton.setObjectName("whiteTagTextButton")
        self.blackTagTextButton = QtWidgets.QPushButton(self.groupBox)
        self.blackTagTextButton.setGeometry(QtCore.QRect(240, 60, 50, 24))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.blackTagTextButton.setPalette(palette)
        self.blackTagTextButton.setText("")
        self.blackTagTextButton.setObjectName("blackTagTextButton")
        self.textTagColorLabel = QtWidgets.QLabel(self.groupBox)
        self.textTagColorLabel.setGeometry(QtCore.QRect(10, 64, 161, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.textTagColorLabel.setFont(font)
        self.textTagColorLabel.setObjectName("textTagColorLabel")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(214, 102, 15, 20))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.getGoProImageButton = QtWidgets.QPushButton(sediGoProDialogBase)
        self.getGoProImageButton.setGeometry(QtCore.QRect(450, 260, 141, 61))
        self.getGoProImageButton.setObjectName("getGoProImageButton")
        self.groupBox_2 = QtWidgets.QGroupBox(sediGoProDialogBase)
        self.groupBox_2.setGeometry(QtCore.QRect(320, 330, 271, 121))
        self.groupBox_2.setObjectName("groupBox_2")
        self.saveImageButton = QtWidgets.QPushButton(self.groupBox_2)
        self.saveImageButton.setGeometry(QtCore.QRect(10, 30, 80, 24))
        self.saveImageButton.setObjectName("saveImageButton")
        self.imageNameLineEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.imageNameLineEdit.setGeometry(QtCore.QRect(10, 80, 191, 24))
        self.imageNameLineEdit.setObjectName("imageNameLineEdit")
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setGeometry(QtCore.QRect(210, 82, 33, 19))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.currentDirectoryLabel = QtWidgets.QLabel(self.groupBox_2)
        self.currentDirectoryLabel.setGeometry(QtCore.QRect(10, 60, 251, 16))
        self.currentDirectoryLabel.setText("")
        self.currentDirectoryLabel.setObjectName("currentDirectoryLabel")
        self.splitter = QtWidgets.QSplitter(sediGoProDialogBase)
        self.splitter.setGeometry(QtCore.QRect(450, 220, 141, 25))
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.batterySlider = QtWidgets.QSlider(self.splitter)
        self.batterySlider.setEnabled(False)
        self.batterySlider.setMaximum(100)
        self.batterySlider.setOrientation(QtCore.Qt.Horizontal)
        self.batterySlider.setObjectName("batterySlider")
        self.spinBox = QtWidgets.QSpinBox(self.splitter)
        self.spinBox.setEnabled(False)
        self.spinBox.setMaximum(100)
        self.spinBox.setObjectName("spinBox")
        self.setGoProOffButton = QtWidgets.QPushButton(sediGoProDialogBase)
        self.setGoProOffButton.setGeometry(QtCore.QRect(450, 80, 51, 24))
        self.setGoProOffButton.setObjectName("setGoProOffButton")
        self.setGoProOnButton = QtWidgets.QPushButton(sediGoProDialogBase)
        self.setGoProOnButton.setEnabled(False)
        self.setGoProOnButton.setGeometry(QtCore.QRect(510, 80, 51, 24))
        self.setGoProOnButton.setObjectName("setGoProOnButton")

        self.retranslateUi(sediGoProDialogBase)
        self.button_box.accepted.connect(sediGoProDialogBase.accept)
        self.button_box.rejected.connect(sediGoProDialogBase.reject)
        self.batterySlider.valueChanged['int'].connect(self.spinBox.setValue)
        QtCore.QMetaObject.connectSlotsByName(sediGoProDialogBase)

    def retranslateUi(self, sediGoProDialogBase):
        _translate = QtCore.QCoreApplication.translate
        sediGoProDialogBase.setWindowTitle(_translate("sediGoProDialogBase", "Sediment image capture with GoPro camera"))
        self.connectionStatusLabel.setText(_translate("sediGoProDialogBase", "Not connected"))
        self.connectGoProCameraButton.setText(_translate("sediGoProDialogBase", "Connect GoPro"))
        self.setWorkingDirectoryButton.setText(_translate("sediGoProDialogBase", "Set working directory..."))
        self.label.setText(_translate("sediGoProDialogBase", "Battery level"))
        self.groupBox.setTitle(_translate("sediGoProDialogBase", "Tag image"))
        self.tagImageButton.setText(_translate("sediGoProDialogBase", "Tag image"))
        self.llRadioButton.setText(_translate("sediGoProDialogBase", "LL"))
        self.lrRadioButton.setText(_translate("sediGoProDialogBase", "LR"))
        self.ulRadioButton.setText(_translate("sediGoProDialogBase", "UL"))
        self.urRadioButton.setText(_translate("sediGoProDialogBase", "UR"))
        self.textTagColorLabel.setText(_translate("sediGoProDialogBase", "Set text color: BLACK"))
        self.label_3.setText(_translate("sediGoProDialogBase", "+"))
        self.getGoProImageButton.setText(_translate("sediGoProDialogBase", "Take image"))
        self.groupBox_2.setTitle(_translate("sediGoProDialogBase", "Save image"))
        self.saveImageButton.setText(_translate("sediGoProDialogBase", "Save image"))
        self.label_2.setText(_translate("sediGoProDialogBase", ".JPG"))
        self.setGoProOffButton.setText(_translate("sediGoProDialogBase", "Off"))
        self.setGoProOnButton.setText(_translate("sediGoProDialogBase", "On"))

